[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=6.0.1"]
build-backend = "setuptools.build_meta"

[project]
name = "modtx"
version = "0.0.0"
authors = [{ name = "Karam Ravindra", email = "contact@karanravindra.me" }]
